project.inet.digital:
  stage: test
  port: 22
  user: root
  forwardAgent: true
  multiplexing: true
  deploy_path: /var/www/project.inet.digital
  branch: test

production:
  stage: production
  port: 22
  user: ec2-user
  forwardAgent: true
  multiplexing: true
  deploy_path: /var/www/project
  branch: production
